version: 2
updates:
  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "python"
    assignees:
      - "cheesejaguar"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      dev-dependencies:
        patterns:
          - "pytest*"
          - "ruff"
          - "mypy"
          - "black"
      
  # JavaScript dependencies
  - package-ecosystem: "npm"
    directory: "/web/frontend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "javascript"
    assignees:
      - "cheesejaguar"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      react:
        patterns:
          - "react*"
          - "@types/react*"
      build-tools:
        patterns:
          - "vite*"
          - "typescript"
          - "tailwindcss"
      
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3
    labels:
      - "dependencies"
      - "github-actions"
    assignees:
      - "cheesejaguar"
    commit-message:
      prefix: "ci"
      include: "scope"