# Run Ruff in the same sequence as CI: format → check → format --check
# Requires ruff to be available in the environment (installed via dev extras).
repos:
  - repo: local
    hooks:
      - id: ruff-format
        name: ruff format (write)
        entry: ruff format
        language: system
        types: [python]
      - id: ruff-check
        name: ruff check (lint)
        entry: ruff check
        language: system
        types: [python]
      - id: ruff-format-check
        name: ruff format --check (verify formatting)
        entry: ruff format --check
        language: system
        types: [python]

