blank_issues_enabled: false
contact_links:
  - name: 💬 Discussions
    url: https://github.com/cheesejaguar/plugah/discussions
    about: Ask questions and discuss ideas with the community.
  - name: 📚 Documentation
    url: https://github.com/cheesejaguar/plugah#readme
    about: Check the README for usage instructions and examples.
  - name: 🤖 Claude Code Instructions
    url: https://github.com/cheesejaguar/plugah/blob/main/CLAUDE.md
    about: Development instructions for working with Claude Code.